server:
  port: 8081

spring:
  application:
    name: ms-listas-espera
  
  # Configuración de base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/listas_espera_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  
  # Configuración de JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Útil en desarrollo para auto-crear tablas
    show-sql: true # Imprime las sentencias SQL en consola

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
